### ISSUE TITLE
new features:

### ISSUE THREAD

**Issue by mohammed-sec2010** [UserExistsError/webshooter#2]
Hello

could you please add an option to save the image with base64  in HTML template instead of showing the pictures in HTML template locally?
you can use this below tool:
https://github.com/joeky888/imgb64

**Comment by UserExistsError** [comment]
Added in https://github.com/UserExistsError/webshooter/commit/2dbbcc3f17e58f74dff4a01e2f9b0810bb1a7ebe.

You can use the `--embed-images` report flag. Note that screenshots are still stored in individual files. This is done so users can view images outside of the report.

**Comment by mohammed-sec2010** [comment]
nice work bro, also add an option for the output  report path

**Comment by mohammed-sec2010** [comment]
Failed to call node: Command '['/usr/local/lib/node/nodejs/bin/node', '/opt/node/webshooter/script._ha2e1oi.js']' timed out after 60 seconds
Screenshot failed: https://maktoob.yahoo.com/?p=us
